// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq4gdsnhuxlkzJFne7mpi5MwZc3oSm3qM',
    appId: '1:375850597015:web:ed6182bd59c7b80c4a47d2',
    messagingSenderId: '375850597015',
    projectId: 'chat-app-3eb72',
    authDomain: 'chat-app-3eb72.firebaseapp.com',
    storageBucket: 'chat-app-3eb72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-0N2f2yE03DgyYh-aIGDdxigH8BpvdJ8',
    appId: '1:375850597015:android:41e481685bb896894a47d2',
    messagingSenderId: '375850597015',
    projectId: 'chat-app-3eb72',
    storageBucket: 'chat-app-3eb72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWXNLDZcCyUyoP1EfL9PMgst7a5Fiavc',
    appId: '1:375850597015:ios:481af8bc3accc1104a47d2',
    messagingSenderId: '375850597015',
    projectId: 'chat-app-3eb72',
    storageBucket: 'chat-app-3eb72.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYWXNLDZcCyUyoP1EfL9PMgst7a5Fiavc',
    appId: '1:375850597015:ios:860985d1e181a4b84a47d2',
    messagingSenderId: '375850597015',
    projectId: 'chat-app-3eb72',
    storageBucket: 'chat-app-3eb72.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
